Show error messages

diff --git a/system/hsConfig b/system/hsConfig
--- a/system/hsConfig
+++ b/system/hsConfig
@@ -8,7 +8,8 @@ then
     echo "END DEFAULT.NIX"
 fi
 echo "Generating default.nix"
-DEF=$(cabal2nix ./.) || exit 1
+DEF=$(cabal2nix ./.) ||
+    { echo "Error: $DEF" >> /dev/stderr; exit 1; }
 
 echo "$DEF" > default.nix
 
@@ -19,7 +20,8 @@ then
     echo "END SHELL.NIX"
 fi
 
-SHELL=$(cabal2nix --shell .) || exit 1
+SHELL=$(cabal2nix --shell .) ||
+    { echo "Shell error: $SHELL" >> /dev/stderr; exit 1; }
 
 echo "$SHELL" > shell.nix
 
