Check for dir in inDir

diff --git a/system/inDir b/system/inDir
--- a/system/inDir
+++ b/system/inDir
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 
-pushd "$1" > /dev/null
-shift 1
+pushd "$1" > /dev/null || {
+    echo "Couldn't enter directory '$1'" 1>&2
+    exit 1
+}
 
+shift 1
 "$@"
 CODE="$?"
 
