Make josyn host configurable

diff --git a/system/josyn b/system/josyn
--- a/system/josyn
+++ b/system/josyn
@@ -1,18 +1,23 @@
 #!/usr/bin/env bash
 
-if ssh jo@debian.local true
+if [[ -z "$JOHOST" ]]
+then
+    JOHOST="debian.local"
+fi
+
+if ssh jo@"$JOHOST" true
 then
   echo "Killing synergy client for nixos" 1>&2
-  ssh jo@debian.local "./killsyn nixos"
+  ssh jo@"$JOHOST" "./killsyn nixos"
 
   echo "Killing synergy server" 1>&2
   killall -9 synergys
 
-  ssh jo@debian.local "./synergy" &
+  ssh jo@"$JOHOST" "./synergy" &
 
   echo "Starting synergy server" 1>&2
   nix-shell -p synergy --run synergys
 else
-  echo "Can't connect to debian.local" 1>&2
+  echo "Can't connect to $JOHOST" 1>&2
   exit 1
 fi
