Give original URL in debug info

diff --git a/web/get_bbc_podcast b/web/get_bbc_podcast
--- a/web/get_bbc_podcast
+++ b/web/get_bbc_podcast
@@ -7,12 +7,12 @@ URL=$(wget -q -O- "$1" | grep -o '<a [^>]*> Higher quality' |
 
 # Sanity check
 echo "$URL" | grep '^http' > /dev/null || {
-    echo "URL '$URL' doesn't begin with http, aborting" 1>&2
+    echo "While fetching '$1', programme URL '$URL' not http, aborting" 1>&2
     exit 1
 }
 
 echo "$URL" | grep 'mp3$' > /dev/null || {
-    echo "URL '$URL' doesn't end in mp3, aborting" 1>&2
+    echo "While fetching '$1', programme URL '$URL' not an mp3, aborting" 1>&2
     exit 1
 }
 
